apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "peacock-api.fullname" . }}-promtail-config
  labels:
    {{- include "peacock-api.labels" . | nindent 4 }}
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: {{ .Values.loki.url }}
    scrape_configs:
    - job_name: system
      static_configs:
      - targets:
          - localhost
        labels:
          job: spring-boot-logs
          __path__: /var/log/containers/*{{ include "peacock-api.fullname" . }}*.log
